global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'app'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:1234']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']